### ISSUE TITLE
[Question] How to get fullPath without creating the File Itself?

### ISSUE THREAD

**Issue by Shabinder** [K1rakishou/Fuck-Storage-Access-Framework#23]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/44765050/118141112-ac746c00-b426-11eb-824b-4cc8ed73e411.png">

In Above Image As you can see I am creating a File with all the segments I need. I just need its **FilePath** as String (uri for saf / path for java.io.File) (I can get that using **AbstractFile.getFilePath()** ) 
But in order to that I need to create an empty File and delete it, Which is very inefficient!

Can you point me what I can do here? or do I need to manually handle it ?
_PS: (What is clone function for?, I really didn't understand that? as literally it should mean cloning the file to new path with its data)_
As far as I can see its implementation, clone is what I am looking for.... am I right?

and thanks for this lib, I don't understand why doesn't Android allow me to write to sdcard using java.io.File when I have asked the permission to whole Tree using ACTION_OPEN_DOCUMENT_TREE !!!!, Really, Fuck SAF.

**Comment by K1rakishou** [comment]
You can use AbstractFile.getFullPath() which will return either a DocumentFile's uri (as string) or File's absolutePath. Basically, in your case you can do File(file.getFullPath).

The clone() function is used to manipulate AbstractFile's segments since it's immutable. Basically it takes segments of AbstractFile you are calling this method upon and adds new segments to the end of the segment list and returns new AbstractFile.

https://github.com/K1rakishou/Fuck-Storage-Access-Framework/blob/842c5fb558fabbeee86629a06c71e09d2f373f2d/fsaf/src/main/java/com/github/k1rakishou/fsaf/file/AbstractFile.kt#L101

**Comment by Shabinder** [comment]
Yup, I accomplished my required task.
Thanks. 👍
